version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/relaybox/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=simonharper
      - POSTGRES_DB=relaybox_core_local

  redis:
    image: redis:7-alpine
    ports:
      - 6390:6379
    volumes:
      - ~/apps/relaybox/redis/data:/root/redis
      - ~/apps/relaybox/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6390
      - REDIS_DATABASES=1

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5682:5672
      - 15682:15672
    volumes:
      - ~/apps/relaybox/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/apps/relaybox/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - rabbitmq_go_net_2

  nginx:
    image: nginx:latest
    ports:
      - 9090:8080
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf

networks:
  rabbitmq_go_net_2:
    driver: bridge
